[package]
name = "rust-succ"
description = "A version of SUCC (Sexy and Utilitarian C# Configuration by Jimmy Cushnie) ported for rust"
version = "0.1.0"
authors = ["DoctorVWA"]
edition = "2018"

[dependencies]
